//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DatabaseEntities : DbContext
{
    public DatabaseEntities()
        : base("name=DatabaseEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<grams3> grams3 { get; set; }
    public DbSet<grams3pos> grams3pos { get; set; }
    public DbSet<Sfarim> Sfarim { get; set; }
    public DbSet<Table> Table { get; set; }
    public DbSet<Tanach> Tanach { get; set; }
}
