//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class grams3
{
    public int freq { get; set; }
    public string firstword { get; set; }
    public string secondword { get; set; }
    public string thirdword { get; set; }
    public int Id { get; set; }
}
